// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRHMgFWw4f4rK5X017ecQSOaMUi2zpZc',
    appId: '1:565023667371:web:68fcddd5038518e4a4b3ee',
    messagingSenderId: '565023667371',
    projectId: 'e-ecommerce-c9786',
    authDomain: 'e-ecommerce-c9786.firebaseapp.com',
    storageBucket: 'e-ecommerce-c9786.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfV6FFW7HfkMt88DUctRvEMxyI7oRgW58',
    appId: '1:565023667371:android:f2ee2f4e2d70ef3ba4b3ee',
    messagingSenderId: '565023667371',
    projectId: 'e-ecommerce-c9786',
    storageBucket: 'e-ecommerce-c9786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Pi7ZXZLXTHxWWLCN-yBSL2-5UU5rmhA',
    appId: '1:565023667371:ios:ab9ade4329fda125a4b3ee',
    messagingSenderId: '565023667371',
    projectId: 'e-ecommerce-c9786',
    storageBucket: 'e-ecommerce-c9786.firebasestorage.app',
    iosBundleId: 'com.example.electro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Pi7ZXZLXTHxWWLCN-yBSL2-5UU5rmhA',
    appId: '1:565023667371:ios:ab9ade4329fda125a4b3ee',
    messagingSenderId: '565023667371',
    projectId: 'e-ecommerce-c9786',
    storageBucket: 'e-ecommerce-c9786.firebasestorage.app',
    iosBundleId: 'com.example.electro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOfBzqq_cNJfGsiRKVKrc3uDQjH36E27o',
    appId: '1:1055120878021:web:e6affb1b75338a43c583ac',
    messagingSenderId: '1055120878021',
    projectId: 'electroapp',
    authDomain: 'electroapp.firebaseapp.com',
    storageBucket: 'electroapp.firebasestorage.app',
    measurementId: 'G-JXFDF7E8TQ',
  );
}
